api = "0.2"

[buildpack]
id = "org.cloudfoundry.php-compat"
name = "PHP Compat Buildpack"
version = "{{ .Version }}"

[metadata]
include_files = ["bin/build","bin/detect","buildpack.toml"]
pre_package = "./scripts/build.sh"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"
